# This is a basic workflow to help you get started with Actions

name: snapshot

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  pull_request_review:
    branches: [main]
    types: [submitted]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  ci-test:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Git Checkout
      - uses: actions/checkout@v2

      - name: use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3.0.0
        with:
          node-version: ${{ matrix.node-version }}

      # # Remove node_modules
      # - name: Remove node_modules
      #   run: rm -rf node_modules/

      # # Yarn Cache Clean
      # - name: Yarn Cache Clean
      #   run: yarn cache clean

      # package Install
      - name: Yarn Install
        run: yarn

      # Test
      - name: Test
        id: test
        run: yarn test

      # Test Update /i Commit & Push
      - name: Test update
        if: ${{ failure() && steps.test.conclusion == 'failure' }}
        id: update
        run: |
          pwd
          echo -n 1 > test/source.txt
          cat test/source.txt
          yarn test-update

      - name: Commit & Push Snapshot
        if: ${{ steps.test.conclusion == 'failure' && steps.update.conclusion == 'success' }}
        uses: EndBug/add-and-commit@v9
        with:
          committer_name: snapshot-bot
          committer_email: snapshot-bot@github.com
          message: 'Snapshot Update'
          add: '.'

  # ci-snapshot:
  #   needs: ci-test
  #   if: ${{ always() && (needs.ci-test.result == 'failure') }}
  #   runs-on: ubuntu-latest

  #   strategy:
  #     matrix:
  #       node-version: [16.x]

  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: use Node.js ${{ matrix.node-version }}
  #       uses: actions/setup-node@v3.0.0
  #       with:
  #         node-version: ${{ matrix.node-version }}

  #     # Test Update
  #     - name: Test update
  #       run: yarn test-update

  #     # Commit & Push
  #     - name: Commit & Push Snapshot
  #       run: |
  #         git add test/.jest-test-results.json
  #         git commit -m "Snapshot Update"
  #         git push
